version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    expose:
      - "8080"  # Expose port 8080 within the Docker network
      - 50000:50000
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7


  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_data:/var/lib/mysql

volumes:
  jenkins_data:



networks:
  default:
    external: true
    name: app
